services:
  orgmai-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orgmai-dev-container
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - GH_TOKEN=${GH_TOKEN}
      - GOPATH=/go
      - PATH=/usr/local/go/bin:${PATH}
    network_mode: "bridge"
    env_file:
      - .env
    stdin_open: true
    tty: true

